### ISSUE TITLE
How to display the result

### ISSUE THREAD

**Issue by 0xjacobb** [kevinperlow/SANS-DFIR-2017#2]
Hey, I have seen your presentation on YouTube, which has shown this tool here to explore Bitcoin addresses. Great work. I have tested first with WIN CMD and it worked. 

How do I now receive the "graphic version" of the result? Which tool do you recommend?

**Comment by kevinperlow** [comment]
Thanks for the great feedback :)

I often use this tool: https://stamm-wilbrandt.de/GraphvizFiddle/

Essentially, you need to add some code before and after the output (the
code in GitHub has an example). Something like:

Digraph {
rankdir = "LR";
"output line 1" -> "other output";
"output line 2" -> "some more stuff";
}

So, encapsulate in brackets, pick your graph direction (Left to Right, Top
to Bottom, etc). And hit go. That website runs locally, it's just some
JavaScript. You can actually save the HTML to your desktop if you'd like.
You could also add the digraph and bracket stuff right into the code, add
some newline breaks, and have it output the full graph but that's a bit
messy for my taste.

There are a few alternative options to explore- Ubuntu has a graphviz/dot
application you could use (I think some of the SANS SIFT/Remnux/REM
machines have it). Python also has a .dot library. But the above is the
easiest.

Let me know if this works for you or if you have any other questions.

**Comment by 0xjacobb** [comment]
Hey thanks for the link. 

Unfortunately, I am still a little bit confused.

>Essentially, you need to add some code before and after the output 

> 

--> Which Output do you mean? Which code?

> (thecode in GitHub has an example). Something like:
Digraph {
rankdir = "LR";
"output line 1" -> "other output";
"output line 2" -> "some more stuff";
}

> 

--> I could not find "Digraph" function...

> So, encapsulate in brackets, pick your graph direction (Left to Right, Topto Bottom, 

> etc)

--> Sorry for that, but this says nothing to me :-)

**Comment by kevinperlow** [comment]
Sorry for the delay. So, when you run the script it will print two sets of items. The first set are the transactions. I have it print those so that you get a sense of how much of the blockchain it's mapping as it goes along. Personal preference, you can turn that off. The second set is a bunch of stuff that looks something like this:

"1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T" -> "1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T";
"1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T" -> "1K9tT2M8jkP1T3LNiuj4NCZsSuTiKt38GH";
"17MuHRgeSKK6nNeiqaWxE5x7ELhBhKmSUY" -> "1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T";
"17MuHRgeSKK6nNeiqaWxE5x7ELhBhKmSUY" -> "16qJVXUZqqXGwYcxByBJmXa6FG9cbq42qk";

These are transactions, represented by the sending address (on the left) and the recipient (on the right). That "->" arrow format is something specific to .dot graphs- essentially, these data flows are designed to be mapped using something called DOT language, often via an engine like Graphviz. The wikipedia article is probably the best starting point. It's a REALLY flexible graphing mechanism, and I use it a lot for other purposes (plotting remote access, mapping threat actors to tools, etc): https://en.wikipedia.org/wiki/DOT_(graph_description_language)

The good news is, these Bitcoin relationships ca be measured using one of the simplest forms of this language. As you'll see below, you just need to "wrap" the data (copy and paste the output the script gives you) in a few things. First, you specify the type of graph (digraph) outside of your graph (kind of like naming a rule before the start of a YARA rule). Then, you can (optionally) specify the direction of the graph (LR for left-right, TB for top-bottom). After that, it's a question of just pasting the data and closing the bracket. Each line should be separated by a semicolon. See below- you can paste this into a site like https://stamm-wilbrandt.de/GraphvizFiddle/ and it will render once you hit "draw."

digraph {
rankdir=LR;

"1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T" -> "1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T";
"1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T" -> "1K9tT2M8jkP1T3LNiuj4NCZsSuTiKt38GH";
"17MuHRgeSKK6nNeiqaWxE5x7ELhBhKmSUY" -> "1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T";
"17MuHRgeSKK6nNeiqaWxE5x7ELhBhKmSUY" -> "16qJVXUZqqXGwYcxByBJmXa6FG9cbq42qk";
"1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T" -> "1Kj1JtcRxhdgx9WwiUVCcrRDWEV6tL85Y";
"1ATAFLWAaT1PNaXJzr7KYZKiD7wweaV7LJ" -> "1BovPQTXTw5xbRcys4RVyUfMitomt9DgZd";
"1ATAFLWAaT1PNaXJzr7KYZKiD7wweaV7LJ" -> "18avTeGBzA9jikaDStQzH2ShfvyQbmaoWT";
"1ATAFLWAaT1PNaXJzr7KYZKiD7wweaV7LJ" -> "1HyasSC2VifTZo7YkUNn33udnWXw3Ffq7T";
"1ATAFLWAaT1PNaXJzr7KYZKiD7wweaV7LJ" -> "1DRRzcZ9YUL8Wdcg1ui2k4ZPHKzk9KeEN5";
"1ATAFLWAaT1PNaXJzr7KYZKiD7wweaV7LJ" -> "1AmeTCjMuq6bHhYkwnqukRsXFExLGmZpsX";
"1ATAFLWAaT1PNaXJzr7KYZKiD7wweaV7LJ" -> "1MoPK3tzouf5jY5mRiJBuTcgzKMxZDPKw1";
"1ATAFLWAaT1PNaXJzr7KYZKiD7wweaV7LJ" -> "1AApZChUfVc3n9uoVwLHy8uVizbm7PU3ZC";
}
